# Generated by Django 4.2 on 2026-03-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meroshare_user', models.CharField(max_length=100, unique=True)),
                ('meroshare_pass', models.CharField(max_length=255)),
                ('dp_name', models.CharField(max_length=255)),
                ('crn', models.CharField(max_length=20)),
                ('tpin', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=255)),
                ('kitta', models.IntegerField(default=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_applied', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.account')),
            ],
        ),
    ]
