# Generated by Django 4.2 on 2026-03-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_account_owner_fcmtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
