# Generated by Django 4.2 on 2026-03-02 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0003_remove_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='meroshare_pass',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('agriculture', 'Agriculture Development Bank Ltd.'), ('citizens', 'Citizens Bank International Ltd.'), ('everest', 'Everest Bank Ltd.'), ('global_ime', 'Global IME Bank Ltd.'), ('himalayan', 'Himalayan Bank Ltd.'), ('kumari', 'Kumari Bank Ltd.'), ('laxmi_sunrise', 'Laxmi Sunrise Bank Ltd.'), ('machhapuchchhre', 'Machhapuchchhre Bank Ltd.'), ('nabil', 'Nabil Bank Ltd.'), ('nepal_bank', 'Nepal Bank Ltd.'), ('nimb', 'Nepal Investment Mega Bank Ltd.'), ('sbi', 'Nepal SBI Bank Ltd.'), ('nic_asia', 'NIC Asia Bank Ltd.'), ('nmb', 'NMB Bank Ltd.'), ('prabhu', 'Prabhu Bank Ltd.'), ('prime', 'Prime Commercial Bank Ltd.'), ('rbb', 'Rastriya Banijya Bank Ltd.'), ('sanima', 'Sanima Bank Ltd.'), ('siddhartha', 'Siddhartha Bank Ltd.'), ('scb', 'Standard Chartered Bank Nepal Ltd.'), ('garima', 'Garima Bikas Bank Ltd.'), ('jyoti', 'Jyoti Bikas Bank Ltd.'), ('kamana', 'Kamana Sewa Bikas Bank Ltd.'), ('lumbini', 'Lumbini Bikas Bank Ltd.'), ('mahalaxmi', 'Mahalaxmi Bikas Bank Ltd.'), ('muktinath', 'Muktinath Bikas Bank Ltd.'), ('shangrila', 'Shangri-la Bikas Bank Ltd.'), ('shine_resunga', 'Shine Resunga Development Bank Ltd.'), ('corporate', 'Corporate Development Bank Ltd.'), ('excel', 'Excel Development Bank Ltd.'), ('green', 'Green Development Bank Ltd.'), ('karnali', 'Karnali Development Bank Ltd.'), ('miteri', 'Miteri Development Bank Ltd.'), ('narayani', 'Narayani Development Bank Ltd.'), ('salapa', 'Salapa Bikas Bank Ltd.'), ('saptakoshi', 'Saptakoshi Development Bank Ltd.'), ('sindhu', 'Sindhu Bikas Bank Ltd.')], default='nic_asia', max_length=50)),
                ('bank_username', models.CharField(max_length=255)),
                ('bank_password', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='automation.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
