# Generated by Django 4.2 on 2026-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_bank_account_and_encryption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_username',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
