# Generated by Django 4.2 on 2026-03-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_remove_bankaccount_bank_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
