# Generated by Django 4.2 on 2026-03-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_applicationlog_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='boid',
            field=models.CharField(blank=True, help_text='16-digit BOID for checking IPO results', max_length=20, null=True),
        ),
    ]
