# Generated by Django 6.0.3 on 2026-03-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_account_boid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner_name',
            field=models.CharField(blank=True, help_text='e.g., Mom, Dad, Me', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BankOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='automation.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
