name: Sync to Hugging Face Space
on:
  push:
    branches: [user-part-1]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: huggingface/github-action@v1
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repository: bishal-2630/ipo-automation
          space: bishal-2630/ipo-automation
          branch: user-part-1
